2. Основы JS. Примитивные типы данных
js-tasks-ru/js-20210309-2_alexey-sitnikov pull request #2
Opened 2021-03-13 19:04 UTC by i2rdt

2021-03-13 19:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-14 14:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let newArr = arr.slice();
проверьте, тут точно `let`?

2021-03-14 14:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-03-14 14:26 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
good 👍

2021-03-14 14:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
good 👍

2021-03-14 14:26 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-14 15:20 UTC, i2rdt commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let newArr = arr.slice();
поправил

2021-03-14 15:22 UTC, i2rdt commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.reverse();
видел на stackoverflow, что с .reverse() якобы быстрее

кусок убрал, порядок сортировки добавил в compare функцию

2021-03-14 15:22 UTC, i2rdt commented
внес правки согласно комментариям

2021-03-16 20:25 UTC, dosandk approved these changes
good 👍

2021-03-16 20:25 UTC, merged